USE [GD2C2016]
GO

DROP TABLE ESE_CU_ELE.RolXFuncionalidad
DROP TABLE ESE_CU_ELE.RolXUsuario
DROP TABLE ESE_CU_ELE.Funcionalidad
DROP TABLE ESE_CU_ELE.Rol
DROP TABLE ESE_CU_ELE.Usuario
DROP TABLE ESE_CU_ELE.Planes

DROP SCHEMA [ESE_CU_ELE]
